const typingParagraphs = [
  "Rainy days often bring a sense of calm and relaxation. The sound of raindrops hitting rooftops and leaves can soothe the mind. Many people enjoy reading a book, sipping hot tea, or simply watching the rainfall through a window. Nature feels refreshed after a shower, and the cool breeze carries a pleasant scent. Whether you're indoors or outside, rainy weather invites moments of reflection and peace that break the rush of daily life.",

  "The solar system consists of eight planets that orbit around the sun. Each planet has unique features and characteristics. Earth is the only one known to support life, while gas giants like Jupiter and Saturn have no solid surface. Mercury is the closest to the sun, and Neptune is the farthest. Understanding the planets helps us learn about our universe and inspires space exploration that could reveal even more fascinating celestial bodies.",

  "Reading is a powerful way to expand the mind and explore new perspectives. Whether it's fiction, history, or science, books provide insights into the human experience. They improve vocabulary, critical thinking, and empathy. Reading regularly also strengthens focus and memory. In a world full of distractions, sitting down with a good book offers a quiet escape and a chance to grow intellectually and emotionally, one page at a time.",

  "Mountains are majestic formations that rise high above the earth’s surface. They’re often covered in forests, snow, or rocky peaks. People visit mountains to hike, climb, or simply enjoy the breathtaking views. Besides their beauty, mountains are home to unique ecosystems and provide freshwater to many regions. Their towering presence inspires awe and reminds us of nature's power and serenity. Life in the mountains may be tough, but it's full of wonder.",

  "Honeybees are essential to the planet’s ecosystem. As pollinators, they help plants grow, breed, and produce food. Without bees, many crops would fail, affecting food supplies worldwide. Bees live in colonies and communicate through a dance known as the 'waggle dance' to share information about flower locations. Unfortunately, bee populations are declining due to pesticides and habitat loss. Protecting bees means protecting biodiversity and ensuring future generations can enjoy a healthy environment.",

  "Music is a universal language that transcends cultures and borders. It has the power to uplift spirits, calm the mind, and even heal emotional wounds. From ancient drums to modern symphonies, music has evolved alongside humanity. People use it to celebrate, mourn, worship, and connect. Whether you're listening through headphones or dancing at a concert, music brings joy and unity to our lives, often saying what words alone cannot express.",

  "Cooking is both a necessity and an art form. While we need food to survive, preparing meals allows creativity to shine. From family recipes passed down through generations to new experiments in the kitchen, cooking connects us with culture and tradition. The aroma of spices, the sound of sizzling pans, and the final taste all play roles in the experience. Sharing a homemade meal is a gesture of love and community.",

  "The ocean covers more than seventy percent of the Earth’s surface and is home to a vast array of marine life. From colorful coral reefs to the mysterious deep sea, oceans support biodiversity and regulate the planet’s climate. They provide food, oxygen, and even medicines. However, pollution and overfishing threaten these ecosystems. Protecting the oceans is not just an environmental duty but also essential for the survival of future generations.",

  "Childhood is a time of curiosity and exploration. Every new experience shapes the way children see the world. From learning to ride a bike to asking endless questions about everything, kids grow mentally and emotionally with every moment. Encouragement, play, and a safe environment help them flourish. These early years build the foundation for future learning, relationships, and resilience. Childhood, though short, often leaves memories and lessons that last a lifetime.",

  "History is a record of human triumphs, struggles, and progress. By studying the past, we gain insights into how societies evolve and how decisions shape the future. Civilizations rise and fall, but their stories continue to influence modern life. Learning history helps us avoid repeating mistakes and appreciate the sacrifices of those who came before. It also inspires us to build a better world grounded in understanding, justice, and wisdom.",

  "Bicycling is a fun and eco-friendly way to travel. It reduces traffic, cuts down pollution, and promotes physical health. Whether commuting to work or cycling through nature trails, riders enjoy the freedom and simplicity of moving on two wheels. Bikes require no fuel and are cheaper to maintain than cars. Plus, regular cycling strengthens muscles and boosts mental well-being. Pedaling through life is good for the body, the environment, and the soul.",

  "Winter transforms the landscape into a silent, snowy wonderland. Trees are covered in frost, and rooftops wear blankets of white. For many, it's a season of cozy evenings, warm clothes, and hot drinks. Winter also brings holidays, snowball fights, and the quiet beauty of falling snow. Though the cold can be harsh, it encourages moments of stillness and reflection. Nature rests, and people find joy in the comfort of warmth and togetherness.",

  "Gardening is a peaceful and rewarding hobby that brings people closer to nature. Planting seeds, watering daily, and watching flowers or vegetables grow is a fulfilling experience. Gardens can be large or small, in backyards or on windowsills. Beyond beauty, gardens provide fresh produce, improve air quality, and support pollinators like bees and butterflies. Gardening teaches patience, responsibility, and appreciation for the earth. It's a simple act that nourishes both body and mind.",

  "Dogs are known as loyal companions and have been part of human life for thousands of years. They offer friendship, protection, and even assistance to those with disabilities. Each breed has unique traits, but all dogs love attention and care. Walking your dog, playing fetch, or simply cuddling can relieve stress and build a strong bond. Their wagging tails and cheerful energy brighten homes and lives in ways few other pets can.",

  "The sky changes constantly—from bright blue mornings to golden sunsets and starry nights. Clouds drift lazily during the day, and stars twinkle silently when darkness falls. Watching the sky can be calming and humbling. It reminds us of how small we are in the vast universe. Whether you're spotting constellations, chasing sunrises, or dreaming under the moonlight, the sky holds endless wonder and invites our thoughts to rise higher with imagination.",

  "Books are portals to other worlds. Through stories, we experience adventures, solve mysteries, and explore emotions. Non-fiction teaches us about the world, while fiction lets us imagine new ones. A book can transport us across time and space without ever leaving our chair. Reading improves focus, vocabulary, and creativity. In a fast-paced world, books offer a moment of calm and depth, reminding us that knowledge and imagination are always within reach.",

  "Language is one of the most powerful tools humans possess. It allows us to express thoughts, share knowledge, and build relationships. Different cultures have developed unique languages, each rich with history and emotion. Learning new languages opens doors to understanding others and appreciating diversity. Whether spoken, signed, or written, language connects us in ways nothing else can. It's the foundation of communication and an essential part of what makes us human.",

  "Birds fill the sky with color and song. From the chirping of sparrows to the powerful flight of eagles, birds are symbols of freedom and grace. They migrate across continents, build intricate nests, and display a wide range of behaviors. Watching birds teaches patience and observation. Many people enjoy birdwatching as a peaceful hobby. Protecting their habitats ensures that these fascinating creatures continue to thrive and inspire us for generations to come.",

  "Sports bring people together through teamwork, discipline, and healthy competition. Whether it's football, cricket, basketball, or tennis, sports help build fitness and confidence. They teach important life skills such as perseverance, cooperation, and leadership. Playing or watching sports creates shared experiences and strong communities. While winning is exciting, the true value lies in effort, improvement, and respect. Sports offer a space to challenge ourselves and celebrate both individual and team achievements.",

  "Autumn is a season of change and beauty. Leaves turn vibrant shades of red, orange, and yellow before falling to the ground. The air becomes crisp, and harvest festivals fill the days with warmth and gratitude. Nature prepares for winter, and people enjoy cozy sweaters, pumpkin-flavored treats, and scenic walks. Autumn invites reflection and slowing down after summer’s rush. It reminds us to appreciate transitions and find beauty in letting go."
];
